services:
  - type: web
    name: study-planner-api
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: FIREBASE_PROJECT_ID
        value: study-schedule-95688
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_USER
        value: smanyela44@gmail.com
      - key: SMTP_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
    autoDeploy: true